# Words, concepts and search

You are given a collection of texts -- let's call it dataset. Each string is a separate document. For each test we will answer exactly 2 questions:
- Which of the documents (`doc_id`) is the closest to a given query?
- How many "concepts" (`concept_count`) are enough to represent this dataset?

Thus your result (answer) will consist of 2 integers, separated by a space. Like this: `doc_id concept_count`.

## Let's consider the test example:

`input.txt`

```
c d b.
d e a.
a b c.
a b c d.
d c a b.
a c.      # <--- the last one is the query
```

## Let's do vectorization
Reuse this in your solutions

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np

inp = """c d b.
d e a.
a b c.
a b c d.
d c a b.
a c.""".split('\n')

dataset, query = inp[:-1], inp[-1]

vect = TfidfVectorizer(
            analyzer='word',
            stop_words=None,
            token_pattern=r"(?u)\b\w+\b"    # (?u)\b\w\w+\b -- default pattern: (?u) -- unicode modifier, \b -- word border, \w\w+ = 2+ letters
)
DTM = vect.fit_transform(dataset).todense()
print("Vocabulary:", vect.get_feature_names())
print(DTM)

print("\nIs it normed?\n")
print(DTM @ DTM.T)

Vocabulary: ['a', 'b', 'c', 'd', 'e']
[[0.         0.57735027 0.57735027 0.57735027 0.        ]
 [0.440627   0.         0.         0.440627   0.78210977]
 [0.57735027 0.57735027 0.57735027 0.         0.        ]
 [0.5        0.5        0.5        0.5        0.        ]
 [0.5        0.5        0.5        0.5        0.        ]]

Is it normed?

[[1.         0.25439612 0.66666667 0.8660254  0.8660254 ]
 [0.25439612 1.         0.25439612 0.440627   0.440627  ]
 [0.66666667 0.25439612 1.         0.8660254  0.8660254 ]
 [0.8660254  0.440627   0.8660254  1.         1.        ]
 [0.8660254  0.440627   0.8660254  1.         1.        ]]


### So, we are ready to answer question 1. 
Which of the documents is the closest to a given query?

In [29]:
query_vector = vect.transform([query]).todense()
cosines_raw = DTM @ query_vector.T # ... oops. Your code here. Compute COSINE SIMILARITIES (1 is match, 0 - orthogonal)
print("Cosine similarities of query and dataset:\n", cosines_raw)
# ... oops. Some more code here. Find an id of the best matching document (string number in test data)
print(f"Best matching document: {cosines_raw.argmax()}")

Cosine similarities of query and dataset:
 [[0.40824829]
 [0.31157034]
 [0.81649658]
 [0.70710678]
 [0.70710678]]
Best matching document: 2


### Time for question 2.
How many concepts are enough to express our dataset?

In other words, how many orthogonal components do we need to pass `allclose` test?

**NB: Can you just take the data and run PCA? Will it change the cosine metric?**

Implement reduced SVD decomposition to pass the test.

In [21]:
U, sigma, Vh = np.linalg.svd(DTM, full_matrices=True)

In [39]:
from numpy.linalg import svd

U, sigma, Vh = np.linalg.svd(DTM, full_matrices=True)
Sigma = np.diag(sigma)
print(U @ Sigma @ Vh)
for i in range(1, min(DTM.shape[1], DTM.shape[0]) + 1):
    doc_embeddings =  U[:, :i] @ Sigma[:i, :]
    projection =  Vh[:, :]
    DTM_approx =  doc_embeddings @ projection
    print(f"If we take {i} components, allclose =", np.allclose(DTM, DTM_approx, atol=0.01))

[[ 5.75035742e-16  5.77350269e-01  5.77350269e-01  5.77350269e-01
  -2.90313134e-16]
 [ 4.40627001e-01 -1.22990992e-16 -4.10234178e-17  4.40627001e-01
   7.82109769e-01]
 [ 5.77350269e-01  5.77350269e-01  5.77350269e-01  1.11369166e-17
   2.44119866e-16]
 [ 5.00000000e-01  5.00000000e-01  5.00000000e-01  5.00000000e-01
   9.33004473e-18]
 [ 5.00000000e-01  5.00000000e-01  5.00000000e-01  5.00000000e-01
   3.47880079e-17]]
(5, 5)
If we take 1 components, allclose = False
(5, 5)
If we take 2 components, allclose = False
(5, 5)
If we take 3 components, allclose = False
(5, 5)
If we take 4 components, allclose = True
(5, 5)
If we take 5 components, allclose = True


In [32]:
k = 4

sig = [sigma[j] if j < k else 0 for j in range(sigma.shape[0])]
Sigma = np.diag(sig)
doc_embeddings =  U @ Sigma 
projection = Vh
query_embedding = projection @ query_vector.T

cosines = doc_embeddings @ query_embedding
print(f"Cosine similarities of query and dataset (after reduction to {k} dimensions):\n", cosines)
assert np.allclose(cosines, cosines_raw), "Cosine similariries are not close"

Cosine similarities of query and dataset (after reduction to 4 dimensions):
 [[0.40824829]
 [0.31157034]
 [0.81649658]
 [0.70710678]
 [0.70710678]]


Exactly the same! We verified the job!

### And the answer is...

Thus, looking at the result of previous block, we can state:
    
`output.txt`
```
2 4
```